---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{ .Chart.Name }}"
    version: "{{ .Values.version }}"
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "api"
    app.kubernetes.io/version: "{{ .Values.build_version }}"
    app.kubernetes.io/managed-by: "Helm"
    chart: "{{ .Chart.Name }}"
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
  name: "{{ .Release.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
      version: "{{ .Values.version }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
        version: "{{ .Values.version }}"
        app.kubernetes.io/name: "{{ .Chart.Name }}"
        app.kubernetes.io/version: "{{ .Values.build_version }}"
        app.kubernetes.io/managed-by: "Helm"
        app.kubernetes.io/part-of: "{{ .Chart.Name }}"
        app.kubernetes.io/component: "api"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: Always
        env:
        - name: DT_TAGS
          value: {{ .Values.dt_tags }}
        - name: DT_CUSTOM_PROP
          value: {{ .Values.dt_custom_prop }}
        - name: DT_RELEASE_VERSION
          value: "{{ .Values.version }}"
        - name: DT_RELEASE_BUILD_VERSION
          value: "{{ .Values.build_version }}"
        - name: DT_RELEASE_PRODUCT
          value: "{{ .Chart.Name }}"
        - name: DT_RELEASE_STAGE
          value: "{{ .Release.Namespace }}"
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 15
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
