
config:
  - app-detect-simplenode-canary: "rule.json"

app-detect-simplenode-canary:
  - name: "/canary/application/app-simplenode-canary.name"
  - applicationId: "/canary/application/app-simplenode-canary.id"
  - pattern: "{{ .Env.INGRESS_PROTOCOL }}://simplenodeservice-canary.{{ .Env.INGRESS_DOMAIN }}"
