config:
    - health-staging: "health-check-monitor.json"
    - health-prod: "health-check-monitor.json"
  
health-staging:
    - name: "webcheck.simplenode-gitlab.staging"
    - url: "{{ .Env.INGRESS_PROTOCOL }}://simplenodeservice-simplenode-gitlab-staging.{{ .Env.INGRESS_DOMAIN }}/api/invoke?url=https://www.dynatrace.com"
    - description: "Health Check for simplenode-gitlab in staging"
    - location: "/infrastructure/synthetic-location/acebox.id"
    - managementZoneId: "/simplenode-gitlab/management-zone/management-zone-staging.id"
    - tag: "/simplenode-gitlab/auto-tag/tagging-staging.name"
    #- applicationId: "/simplenode/application/app-simplenode-staging.id"
    - enabled: "true"

health-prod:
    - name: "webcheck.simplenode-gitlab.production"
    - url: "{{ .Env.INGRESS_PROTOCOL }}://simplenodeservice-simplenode-gitlab-production.{{ .Env.INGRESS_DOMAIN }}/api/invoke?url=https://www.dynatrace.com"
    - description: "Health Check for simplenode-gitlab in production"
    - location: "/infrastructure/synthetic-location/acebox.id"
    - managementZoneId: "/simplenode-gitlab/management-zone/management-zone-prod.id"
    - tag: "/simplenode-gitlab/auto-tag/tagging-prod.name"
    #- applicationId: "/simplenode/application/app-simplenode-prod.id"
    - enabled: "true"