monaco_v2_srg:
  image: localhost:32000/monaco:dev
  stage: init
  variables:
    MANIFEST_FILE: ./monaco-v2/manifest.yaml
  script:
    - pwd
    - ls ./monaco-v2
    - echo $MANIFEST_FILE
    - monaco deploy $MANIFEST_FILE --project srg --dry-run
    - monaco deploy $MANIFEST_FILE --project srg
  when: manual


run-tests:
  before_script:
    - echo $(date -u +"%Y-%m-%dT%H:%M:%SZ") > srg.test.starttime
  after_script:
    - echo $(date -u +"%Y-%m-%dT%H:%M:%SZ") > srg.test.endtime
  stage: test
  variables:
    LOCUST_LOCUSTFILE: locust/locustfile.py
    LOCUST_CONFIG: locust/locust.conf
    LOCUST_HOST: "http://simplenodeservice.$DT_RELEASE_STAGE"
    LOCUST_LOAD_TEST_NAME: "Loadtest - $DT_RELEASE_BUILD_VERSION"
  image: locustio/locust
  script:
    - locust --config $LOCUST_CONFIG --locustfile $LOCUST_LOCUSTFILE --host $LOCUST_HOST
  artifacts:
    paths:
      - srg.test.starttime
      - srg.test.endtime

trigger_srg_and_receive_result:
  image: dynatraceace/dt-automation-cli:0.0.2
  stage: evaluate
  variables:
    GUARDIAN_NAME: simplenode-gitlab
  script:
    - eval_start=$(cat srg.test.starttime)
    - eval_end=$(cat srg.test.endtime)
    - export LOG_LEVEL=verbose
    - /dt-automation-cli-linux srg-evaluation -u $DT_TENANT_URL -t $DT_SRG_API_TOKEN -w -s -st $eval_start -et $eval_end $GUARDIAN_NAME
